services:
  metabase-db:
    image: postgres:16-alpine
    container_name: metabase-db
    environment:
      POSTGRES_DB: metabase_app
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabasepwd
    volumes:
      - mb_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_SITE_URL: "http://localhost:3000"
      MB_DB_TYPE: "postgres"
      MB_DB_HOST: "metabase-db"
      MB_DB_PORT: "5432"
      MB_DB_DBNAME: "metabase_app"
      MB_DB_USER: "metabase"
      MB_DB_PASS: "metabasepwd"
      MB_ENCRYPTION_SECRET: "icomoninframetabasepassword"
    depends_on:
      - metabase-db
    volumes:
      - mb_plugins:/plugins
    restart: unless-stopped

volumes:
  mb_pgdata:
  mb_plugins:

